# TODO: This file is in the wrong module. The api shouldn't care about which db is used in business
spring:
  application:
    name: MyBiz - API
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mybiz
    username: mybiz
    password: mybiz
    driverClassName: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false

---

spring:
  profiles: test
  jpa:
    database-platform: H2
  datasource:
    platform: h2
    url: "jdbc:h2:mem:;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    driverClassName: org.h2.Driver

#logging:
#  level:
#    ROOT: DEBUG
